version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/app
      - ./.docker/nginx/conf:/etc/nginx/conf.d
      - ./.docker/nginx/logs:/var/log/nginx
volumes:
  xhprof-dir:
